"""Backward-compatible re-exports — prefer dimos.ar.registration.tracker."""

from dimos.ar.registration.tracker import (  # noqa: F401
    CAMERA_FRAME_MAGIC,
    DEFAULT_MARKER_ID,
    DEFAULT_APRILTAG_DICT,
    MAX_HEADER_BYTES,
    R_ALIGN,
    TAG_BLACK_SIZE_M,
    TAG_TOTAL_SIZE_M,
    FrameResult,
    RobotAprilTagTracker,
    RobotAprilTagTrackerConfig,
    TagMount,
    TagObservation,
    TagSolve,
    build_T_world_odom,
    build_camera_info,
    create_apriltag_detector,
    parse_camera_frame,
    reprojection_error_px,
    solve_yaw_translation_2d,
    _odom_tag_straightness,
    _orientation_yaw_deg,
    _yaw_from_T,
)
